name: ML Code Integration Tests for mlops-demo-classifier

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'databricks-config/**'

env:
  DATABRICKS_HOST: https://e2-demo-emea.cloud.databricks.com/
  NODE_TYPE_ID: i3.xlarge
  DATABRICKS_TOKEN: ${{secrets.STAGING_WORKSPACE_TOKEN}}
jobs:
  staging:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Train model
        uses: databricks/run-notebook@v0
        id: train
        with:
          local-notebook-path: notebooks/Train.py
          git-commit: ${{ github.event.pull_request.head.sha || github.sha }}
          new-cluster-json: >
            {
              "spark_version": "11.0.x-cpu-ml-scala2.12",
              "node_type_id": "${{ env.NODE_TYPE_ID }}",
              "num_workers": 0,
              "spark_conf": {
                "spark.databricks.cluster.profile": "singleNode",
                "spark.master": "local[*, 4]"
              },
              "custom_tags": {
                "ResourceClass": "SingleNode"
              }
            }
          access-control-list-json: >
            [
              {
                "group_name": "users",
                "permission_level": "CAN_VIEW"
              }
            ]
          run-name: mlops-demo-classifier Integration Test
          notebook-params-json: >
            {
              "env": "staging",
              "test_mode": "True"
            }            
